src/src/Entity/BlogPost.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BlogPostRepository")
 */
class BlogPost
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $summary;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creation_date;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $creator_id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_visible;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_adding_comment;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_adding_comment_anonymous;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(?string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getCreatorId(): ?int
    {
        return $this->creator_id;
    }

    public function setCreatorId(?int $creator_id): self
    {
        $this->creator_id = $creator_id;

        return $this;
    }

    public function getIsVisible(): ?bool
    {
        return $this->is_visible;
    }

    public function setIsVisible(bool $is_visible): self
    {
        $this->is_visible = $is_visible;

        return $this;
    }

    public function getComments(): ?string
    {
        return $this->comments;
    }

    public function setComments(?string $comments): self
    {
        $this->comments = $comments;

        return $this;
    }

    public function getIsAddingComment(): ?bool
    {
        return $this->is_adding_comment;
    }

    public function setIsAddingComment(bool $is_adding_comment): self
    {
        $this->is_adding_comment = $is_adding_comment;

        return $this;
    }

    public function getIsAddingCommentAnonymous(): ?bool
    {
        return $this->is_adding_comment_anonymous;
    }

    public function setIsAddingCommentAnonymous(bool $is_adding_comment_anonymous): self
    {
        $this->is_adding_comment_anonymous = $is_adding_comment_anonymous;

        return $this;
    }
}

src/src/Entity/Comments.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentsRepository")
 */
class Comments
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $add_date;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $user_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getAddDate(): ?\DateTimeInterface
    {
        return $this->add_date;
    }

    public function setAddDate(\DateTimeInterface $add_date): self
    {
        $this->add_date = $add_date;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(?int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/src/Controller/EtiController.php
<?php

namespace App\Controller;

use App\Entity\BlogPost;
use App\Entity\Comments;
use App\Entity\User;
use App\Form\AddPostType;
use App\Form\CommentType;
use App\Form\EditingAccountType;
use App\Form\EditPostType;
use App\Repository\BlogPostRepository;
use App\Repository\CommentsRepository;
use App\Repository\UserRepository;
use Exception;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/", name="post.")
 */
class EtiController extends AbstractController
{
    /**
     * @Route("/", name="homepage")
     * @return Response
     */
    public function blogHomepage()
    {
        return $this->render('eti/blog/homepage.html.twig');
    }

    /**
     * @Route("/first/page", name="first_page")
     * @param TranslatorInterface $translator
     * @return Response
     * @throws Exception
     */
    public function randomNumber(TranslatorInterface $translator)
    {
        $number = random_int(0, 100);

        return $this->render('eti/blog/first_page.html.twig', [
            'number' => $number,
            'translated_php' => $translator->trans('Translated string'),
            'translated_php_pl' => $translator->trans('Translated string', [], 'messages', 'pl_PL')
        ]);
    }


    /**
     * @Route("posts/list", name="post_listing")
     *
     * @param BlogPostRepository $blogPostRepository
     * @return Response
     */
    public function listBlogPosts(BlogPostRepository $blogPostRepository)
    {
        $articles = $blogPostRepository->findBy([
            'is_visible' => true
        ]);

        if ($this->getUser() != null) {
            $user = $this->getUser()->getId();
        } else $user = null;

        return $this->render('eti/blog/posts.html.twig', [
            'articles' => $articles,
            'posts' => "Posts",
            'user' => $user
        ]);
    }


    /**
     * @Route("posts/view/{id}", name="post_details")
     *
     * @param Request $request
     * @param BlogPost $blogPost
     * @param CommentsRepository $commentsRepository
     * @return Response
     */
    public function postDetails(Request $request, BlogPost $blogPost, CommentsRepository $commentsRepository)
    {
        if ($blogPost->getIsVisible() == false && $this->getUser() == null) {
            return $this->render('errors/unauthorized.html.twig');
        }

//        if ($blogPost->getIsAddingCommentAnonymous() == true || $blogPost->getIsAddingComment() == true && $this->getUser() != null) {
//
//        }
        $commentString = explode('/', $blogPost->getComments());
        $numberOfComments = sizeof($commentString)-1;

        $idComments = [];
        for ($i = 0; $i < $numberOfComments; $i++) {
            array_push($idComments, $commentString[$i]);
        }

        $allComments = $commentsRepository->findBy([
            'id' => $idComments
        ], [
            'add_date' => 'DESC'
        ]);

        $newComment = new Comments();
        $form = $this->createForm(CommentType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $content = $form->getData()->getcontent();

            if ($this->getUser() == true){
                $user = $this ->getUser()->getUsername();
                $idUser = $this->getUser()->getId();
            } else {
                $user = null;
                $idUser = null;
            }


            $newComment->setUsername($user);
            $newComment->setContent($content);
            $newComment->setAddDate(new \DateTime());
            $newComment->setUserId($idUser);


            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($newComment);
            $entityManager->flush();

            $idComment = $newComment->getId();
            $idPost = $blogPost->getId();
            $entityManagerBlogPost = $this->getDoctrine()->getManager();
            $managerPost = $entityManagerBlogPost->getRepository(BlogPost::class)->find([
                'id' => $idPost
            ]);
            if ($blogPost->getComments() == null) {
                $updateCommentInPost = $idComment . '/';
            } else {
                $updateCommentInPost = $blogPost->getComments() . $idComment . '/';
            }
            $managerPost->setComments($updateCommentInPost);
            $entityManagerBlogPost->flush();

            $this->addFlash(
                'notice',
                'Your comment were added!'
            );
        }

        return $this->render('eti/blog/post_view.html.twig', [
            'article' => $blogPost,
            'comments' => $allComments,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/hidden_content", name="hidden_content")
     * @param UserRepository $userRepository
     * @return Response
     */
    public function hiddenContent(UserRepository $userRepository)
    {
        $userId = $this->getUser()->getId();
        $userName = $this->getUser()->getUsername();

        return $this->render('eti/blog/hidden_content.html.twig', [
            'userId' => $userId,
            'userName' => $userName
        ]);
    }

    /**
     * @Route("/posts/for_users_logged", name="for_logged_users")
     * @param BlogPostRepository $blogPostRepository
     * @return Response
     */
    public function postLoggedUsers(BlogPostRepository $blogPostRepository)
    {
        $id = $this->getUser()->getId();
        $articles = $blogPostRepository->findBy([
            'is_visible' => false
        ]);

        return $this->render('eti/blog/posts.html.twig', [
            'articles' => $articles,
            'posts' => "Hidden posts",
            'user' => $id
        ]);
    }

    /**
     * @Route("/post/add", name="add_post")
     * @param Request $request
     * @return Response
     */
    public function addPost(Request $request)
    {
        $post = new BlogPost();
        $id = $this->getUser()->getId();

        $form = $this->createForm(AddPostType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $title = $form->getData()->getTitle();
            $summary = $form->getData()->getSummary();
            $content = $form->getData()->getContent();
            $isVisible = $form->getData()->getIsVisible();
            $isAddingComment = $form->getData()->getIsAddingComment();
            $isAddingCommentAnonymous = $form->getData()->getIsAddingCommentAnonymous();

            $post->setTitle($title);
            $post->setSummary($summary);
            $post->setContent($content);
            $post->setCreationDate(new \DateTime());
            $post->setCreatorId($id);
            $post->setIsVisible($isVisible);
            $post->setIsAddingComment($isAddingComment);
            $post->setIsAddingCommentAnonymous($isAddingCommentAnonymous);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($post);
            $entityManager->flush();

            $this->addFlash(
                'notice',
                'Your post were added!!'
            );
        }

        return $this->render('eti/blog/add_post.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("post/user", name="user_post")
     * @param Request $request
     * @param BlogPostRepository $blogPostRepository
     * @return Response
     */
    public function userPost(Request $request, BlogPostRepository $blogPostRepository)
    {
        $id = $this->getUser()->getId();
        $articles = $blogPostRepository->findBy([
            'creator_id' => $id
        ]);

        return $this->render('eti/blog/posts.html.twig', [
            'articles' => $articles,
            'posts' => "Your posts",
            'user' => $id
        ]);
    }

    /**
     * @Route("post/edit/{id}", name="edit_post")
     * @param BlogPost $blogPost
     * @param Request $request
     * @return Response
     */
    public function editPost(BlogPost $blogPost, Request $request)
    {
        $user_id = $this->getUser()->getId();
        $creator_id = $blogPost->getCreatorId();

        if ($user_id != $creator_id) {
            return $this->render('errors/unauthorized.html.twig');
        }

        $postId = $blogPost->getId();

        $entityManager = $this->getDoctrine()->getManager();
        $postManager = $entityManager->getRepository(BlogPost::class)->find($postId);


        $form = $this->createForm(EditPostType::class, $postManager);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $title = $form->getData()->getTitle();
            $summary = $form->getData()->getSummary();
            $content = $form->getData()->getContent();
            $isVisible = $form->getData()->getIsVisible();
            $isAddingComment = $form->getData()->getIsAddingComment();
            $isAddingCommentAnonymous = $form->getData()->getIsAddingCommentAnonymous();

            $postManager->setTitle($title);
            $postManager->setSummary($summary);
            $postManager->setContent($content);
            $postManager->setIsVisible($isVisible);
            $postManager->setIsAddingComment($isAddingComment);
            $postManager->setIsAddingCommentAnonymous($isAddingCommentAnonymous);

            $entityManager->flush();

            $this->addFlash(
                'notice',
                'Your changes were saved!'
            );
        }

        return $this->render('eti/blog/edit_post.html.twig', [
            'form' => $form->createView(),

        ]);
    }
}

src/templates/eti/blog/add_post.html.twig
{# templates/account/index.html.twig #}
{% extends 'eti/blog/layout.html.twig' %}

{% block title %}Adding post{% endblock %}

{% block content %}
    {% for message in app.flashes('notice') %}
        <div class="flash-notice">
            {{ message }}
        </div>
    {% endfor %}
    <p>Adding post{{ "</br>" }}</p>
    <p> {{ form(form) }} </p>

{% endblock %}

src/templates/eti/blog/edit_post.html.twig
{% extends 'eti/blog/layout.html.twig' %}

{% block title %}Edit post{% endblock %}

{% block content %}
    {% for message in app.flashes('notice') %}
        <div class="flash-notice">
            {{ message }}
        </div>
    {% endfor %}

    <p> Edit post: </p>

    <ul>
        {{ form(form) }}
    </ul>
{% endblock %}

src/templates/eti/blog/first_page.html.twig
{# templates/blog/first_page.html.twig #}
{% extends 'eti/blog/layout.html.twig' %}

{% block title %}Blog Index / FirstPage{% endblock %}

{% block content %}
    <p> Lucky number: {{ number }} </p>
    <div>
        <p>Default PHP translation: {{ translated_php }} <br />
        Template translation: {% trans %}Translated string{% endtrans %}</p>
    </div>
    <div>
        <p>Forced PL translation: {{ translated_php_pl }}<br />
        PL Forced Template translation: {{ 'Translated string'|trans({}, 'messages', 'pl_PL') }}</p>
    </div>
{% endblock %}

src/templates/eti/blog/hidden_content.html.twig
{# templates/eti/blog/hidden_content.html.twig #}

{% extends 'eti/blog/layout.html.twig' %}

{% block title %}Hidden content{% endblock %}

{% block content %}
    <p> Hello, {{ "</br>" }}
    Your id is {{ userId }} and the name is {{ userName }}.
    </p>
{% endblock %}

src/templates/eti/blog/homepage.html.twig
{# templates/eti/blog/homepage.html.twig #}

{% extends 'eti/blog/layout.html.twig' %}

{% block title %}Homepage{% endblock %}

{% block content %}
    <p> Welcome on ETI Blog Homepage! </p>
{% endblock %}

src/templates/eti/blog/layout.html.twig
{# templates/blog/layout.html.twig #}
{% extends 'base.html.twig' %}

{% block body %}
    <h1>ETI Blog</h1>

    {% block content %}{% endblock %}
{% endblock %}

src/templates/eti/blog/post_view.html.twig
{# templates/blog/first_page.html.twig #}
{% extends 'eti/blog/layout.html.twig' %}

{% block title %}Blog Index / Articles to read{% endblock %}

{% block content %}
    <p> {{ article.title }}: </p>

    <ul>
        {{ article.content }}
    </ul>
    {% for message in app.flashes('notice') %}
        <div class="flash-notice">
            {{ message }}
        </div>
    {% endfor %}
    <p>Add comment:</p>
    {% if article.isAddingCommentAnonymous == true or article.isAddingComment == true and app.user != null %}
        {{ form(form) }}
    {% elseif article.isAddingCommentAnonymous == false and article.isAddingComment == true %}
        You must log on to comment on this post
    {% elseif article.isAddingCommentAnonymous == false and article.isAddingComment == false %}
        Comments off
    {% endif %}
    <p> Comments: </p>
    {% for comment in comments %}
        <ul>
            <li>{{ comment.username }}</li>
            <li>{{ comment.addDate|date("Y-m-d H:m:i") }}</li>
            <li>{{ comment.content }}</li>
            <br><br>
        </ul>
    {% endfor %}
{% endblock %}

src/templates/eti/blog/posts.html.twig
{# templates/blog/first_page.html.twig #}
{% extends 'eti/blog/layout.html.twig' %}

{% block title %}Articles to read{% endblock %}

{% block content %}
    <p> {{ posts }} </p>

    <ul>
    {% for article in articles %}
        <li>
            <a href="{{ path('post.post_details', {id:article.id}) }}">
                {{ article.title }} - {{ article.summary }}
            </a>
            {% if app.user and article.creatorId == user %}
                <a href="{{ path ('post.edit_post', {id:article.id}) }}">
                    Edit
                </a>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
{% endblock %}